CREATE TABLE rasp (
  id INTEGER PRIMARY KEY,
  match_date DATE NOT NULL,
  match_time TIME WITH TIME ZONE, 
  first_team INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  second_team INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT different_teams CHECK (first_team != second_team)
)

CREATE TABLE teams (
  id INTEGER PRIMARY KEY,
  tname VARCHAR(30) NOT NULL
)

CREATE TABLE players (
  id INTEGER PRIMARY KEY,
  fio TEXT NOT NULL ,
  team_id INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  tnumber INTEGER
)