CREATE TABLE rasp (
  id SERIAL PRIMARY KEY,
  match_date DATE NOT NULL,
  match_time TIME WITH TIME ZONE, 
  first_team INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  second_team INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT different_teams CHECK (first_team != second_team)
)

CREATE TABLE teams (
  id SERIAL PRIMARY KEY,
  tname VARCHAR(30) NOT NULL
)

CREATE TABLE players (
  id SERIAL PRIMARY KEY,
  fio TEXT NOT NULL,
  team_id INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  tnumber INTEGER 
)

CREATE TABLE archive (
  id SERIAL PRIMARY KEY,
  match_date DATE NOT NULL,
  match_time TIME WITH TIME ZONE,
  first_team INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  res_one INTEGER NOT NULL,
  second_team INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  res_two INTEGER NOT NULL,
  penalty BOOLEAN DEFAULT false,
  winner INTEGER NOT NULL REFERENCES teams (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT different_teams CHECK (first_team != second_team)
)